notemp: true
printshellcmds: false
keep-going: true
resources: ['network_connections=3', 'mem_mb=250000']
use-conda: true
conda-frontend: 'mamba'
conda-prefix: '/Users/byronsmith/.snakemake/conda'
use-singularity: false
config: ['USE_CUDA=0', 'MAX_THREADS=24', 'jupyter_port=8818']
